apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      filelog:
        include: [ /var/log/pods/*/*/*.log ]
        start_at: beginning
        operators:
          - type: regex_parser
            regex: '^(?P<time>\\S+) (?P<stream>stdout|stderr) (?P<logtag>\\w) (?P<log>.*)$'
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: move
            from: attributes.log
            to: body
    processors:
      batch: {}
    exporters:
      debug: {}
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [debug]
